api_creds:
    API_KEY: 1WrxJR6AEzqqspzVlzdKUSHPJ
    API_SECRET: CeJMSOlMqBBSiwqPOy7gw5gxZ3YwtflOC5BZgQcEcutTdfUeFS
    ACCESS_TOKEN: 1243303216978243590-6k8EZCwLX0dkjctXy759wdD3bf1Bli
    ACCESS_SECRET: 7Vs4wjTQnkvlFqKajxnWMqlF3I2s1ijO0dzkjnXrNPshh